FROM python:3.12-slim

RUN useradd -m -u 1000 appuser

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/srgkr/ptai-api-browser.git .
RUN pip3 install --no-cache-dir -r requirements.txt

USER appuser

EXPOSE 8501

CMD ["streamlit", "run", "ptai-browser-api.py", "--server.port=8501", "--server.address=0.0.0.0"]

